Handle AnonymousUser in handle_public_name
This fixes the following error that can occur if this function is called
on an AnonymousUser:

    AttributeError: 'AnonymousUser' object has no attribute 'get_full_name'